---
title: "data_preparation"
output: html_document
---

```{r}
library(tidyverse)
```

### 1 Combined human data and create gene table
```{r create human gene table}
# load data
gm18558 <- read_table("results/GM18558_Zeb2_neg.featureCounts.jcounts")
gm18960 <- read_table("results/GM18960_Zeb2_neg.featureCounts.jcounts")
gm19240 <- read_table("results/GM19240_Zeb2_neg.featureCounts.jcounts")

# remove gene name is NA, and select gene count
gm18558 <- drop_na(gm18558[,c(1,9)])
gm18960 <- drop_na(gm18960[,c(1,9)])
gm19240 <- drop_na(gm19240[,c(1,9)])

# merge and count mean
gm18558 <- aggregate(gm18558[,2], list(gm18558$PrimaryGene), mean)
gm18960 <- aggregate(gm18960[,2], list(gm18960$PrimaryGene), mean)
gm19240 <- aggregate(gm19240[,2], list(gm19240$PrimaryGene), mean)

hm.gene <- inner_join(gm18558, gm18960, by="Group.1")
hm.gene <- inner_join(hm.gene, gm19240, by = "Group.1")
colnames(hm.gene) <- c("gene", "GM18558", "GM18960", "GM19240")
hm.gene <- hm.gene %>%
  mutate(GM18558 = round(GM18558), GM18960 = round(GM18960), GM19240 = round(GM19240))

write.table(hm.gene, "counts/hm_gene.csv", sep=",")
```

### 2 combined chimpanzee data and create gene table
```{r create chimpanzee table}
# load data
judith <- read_table("results/Chimp_Judith_Zeb2_neg.featureCounts.jcounts")
leo <- read_table("results/Chimp_Leo_Zeb2_neg.featureCounts.jcounts")
maryke <- read_table("results/Chimp_Maryke_Zeb2_neg.featureCounts.jcounts")

# remove NA and select gene count
judith <- drop_na(judith[,c(1,9)])
leo <- drop_na(leo[,c(1,9)])
maryke <- drop_na(maryke[,c(1,9)])

# merge and count mean
judith <- aggregate(judith[, 2], list(judith$PrimaryGene), mean)
leo <- aggregate(leo[,2], list(leo$PrimaryGene), mean)
maryke <- aggregate(maryke[,2], list(maryke$PrimaryGene), mean)

chimp.gene <- inner_join(judith, leo, by="Group.1")
chimp.gene <- inner_join(chimp.gene, maryke, by="Group.1")
colnames(chimp.gene) <- c("gene", "Judith", "Leo", "Maryke")

chimp.gene <- chimp.gene %>%
  mutate(Judith = round(Judith), Leo = round(Leo), Maryke = round(Maryke)) %>%
  mutate(gene = substr(gene, 1, 18)) # remove decimal ensembl id

write.table(chimp.gene, "counts/chimp_gene.csv", sep=",")
```

### 3 combined orangutans data and create gene table
```{r}
guchi <- read_table("results/Orang_Guchi_Zeb2_neg.featureCounts.jcounts")
jaqo <- read_table("results/Orang_Jaqo_Zeb2_neg.featureCounts.jcounts")
jingjing <- read_table("results/Orang_JingJing_Zeb2_neg.featureCounts.jcounts")

# remove NA and select gene count
guchi <- drop_na(guchi[,c(1,9)])
jaqo <- drop_na(jaqo[,c(1,9)])
jingjing <- drop_na(jingjing[,c(1,9)])

# merge and count mean
guchi <- aggregate(guchi[,2], list(guchi$PrimaryGene), mean)
jaqo <- aggregate(jaqo[,2], list(jaqo$PrimaryGene), mean)
jingjing <- aggregate(jingjing[,2], list(jingjing$PrimaryGene), mean)

oran.gene <- inner_join(guchi, jaqo, by="Group.1")
oran.gene <- inner_join(oran.gene, jingjing, by="Group.1")
colnames(oran.gene) <- c("gene", "Guchi", "Jaqo", "Jingjing")

oran.gene <- oran.gene %>%
  mutate(
    Guchi = round(Guchi),
    Jaqo = round(Jaqo),
    Jingjing = round(Jingjing),
    gene = substr(gene, 1, 18)
  )

write.table(oran.gene, file = "counts/oran_gene.csv", sep=",")

```

### 4. Human TE data
```{r}
h1 <- read_table("tecount/GM18558_Zeb2_neg.cntTable")
h2 <- read_table("tecount/GM18960_Zeb2_neg.cntTable")
h3 <- read_table("tecount/GM19240_Zeb2_neg.cntTable")

h1 <- h1[!grepl("ENSG", h1$`gene/TE`),]
h2 <- h2[!grepl("ENSG", h2$`gene/TE`),]
h3 <- h3[!grepl("ENSG", h3$`gene/TE`),]

h1 <- h1 %>% separate(
  `gene/TE`,
  c("name", "family", "class"),
  sep = ":"
)
colnames(h1)[4] <-"GM18558" 

colnames(h2)[2] <- "GM18960"
colnames(h3)[2] <- "GM19240"

hm.te <- cbind(h1, h2[,2], h3[,2])
write.table(hm.te, "counts/hm_te.csv", sep=",")
```

### 5. Chimpanzee TE data
```{r}
c1 <- read_table("tecount/Chimp_Judith_Zeb2_neg.cntTable")
c2 <- read_table("tecount/Chimp_Leo_Zeb2_neg.cntTable")
c3 <- read_table("tecount/Chimp_Maryke_Zeb2_neg.cntTable")

c1 <- c1[!grepl("ENS", c1$`gene/TE`),]
c2 <- c2[!grepl("ENS", c2$`gene/TE`),]
c3 <- c3[!grepl("ENS", c3$`gene/TE`),]

c1 <- c1 %>% separate(
  `gene/TE`,
  c("name", "family", "class"),
  sep = ":"
)
colnames(c1)[4] <-"Judith" 
colnames(c2)[2] <- "Leo"
colnames(c3)[2] <- "Maryke"

chimp.te <- cbind(c1, c2[,2], c3[,2])
chimp.te <- chimp.te[-1,]
rownames(chimp.te) <- 1:1260
write.table(chimp.te, "counts/chimp_te.csv", sep=",")
```


### 6. Orangutan TE data
```{r}
o1 <- read_table("tecount/Orang_Guchi_Zeb2_neg.cntTable")
o2 <- read_table("tecount/Orang_Jaqo_Zeb2_neg.cntTable")
o3 <- read_table("tecount/Orang_JingJing_Zeb2_neg.cntTable")

o1 <- o1[!grepl("ENS", o1$`gene/TE`),]
o2 <- o2[!grepl("ENS", o2$`gene/TE`),]
o3 <- o3[!grepl("ENS", o3$`gene/TE`),]

o1 <- o1 %>% separate(
  `gene/TE`,
  c("name", "family", "class"),
  sep = ":"
)
colnames(o1)[4] <-"Guchi" 
colnames(o2)[2] <- "Jaqo"
colnames(o3)[2] <- "Jingjing"

oran.te <- cbind(o1, o2[,2], o3[,2])
write.table(oran.te, "counts/oran_te.csv", sep=",")
```

