---
title: "TEKRABber_hm_oran"
output: html_document
---

```{r}
library(TEKRABber)
library(tidyverse)
```

### 1 download ortholog information
```{r}
# load data
hmGene <- read.csv("counts/hm_gene.csv")
hmTE <- read.csv("counts/hm_te.csv")
hmTE <- hmTE[,c(1,4,5,6)]
oranGene <- read.csv("counts/oran_gene.csv")
oranTE <- read.csv("counts/oran_te.csv")
oranTE <- oranTE[,c(1,4,5,6)]

fetchData <- orthologScale(
  geneCountRef = hmGene,
  geneCountCompare = oranGene,
  speciesRef = 'hsapiens',
  speciesCompare = 'pabelii'
)
```

### 2 create input dataframes for DE expressed analysis and correlation estimation
```{r}
inputBundle <- DECorrInputs(
  orthologTable = fetchData$orthologTable,
  scaleFactor = fetchData$scaleFactor,
  geneCountRef = hmGene,
  geneCountCompare = oranGene,
  teCountRef = hmTE,
  teCountCompare = oranTE
)
```
### 3 DE analysis
```{r}
meta <- data.frame(
  species = c(rep("human", ncol(hmGene)-1), 
              rep("orangutans", ncol(oranGene)-1))
)

meta$species <- factor(meta$species, levels = c("human", "orangutans"))
rownames(meta) <- colnames(inputBundle$geneInputDESeq2)
hmoranDE <- DEgeneTE(
  geneTable = inputBundle$geneInputDESeq2,
  teTable = inputBundle$teInputDESeq2,
  metadata = meta,
  contrastVector = c("species", "human", "orangutans"),
  expDesign = TRUE
)

```
### Correlation analysis
We need to filter KRAB-ZNFs from gene list
for viewing the result from appTEKRABber, you need to use Ensembl ID instead of gene name.
```{r}
# load kznfs 
hm337 <- read.csv("counts/human337KZNFs.csv")
ensembl_id <- c(hm337$ensembl_gene_id, "ENSG00000130726") # ENSG00000130726 = KAP1, TRIM28

# load ortholog data
hmGeneCorrInput <- inputBundle$geneCorrInputRef
hmGeneCorrInput <- hmGeneCorrInput[rownames(hmGeneCorrInput) %in% ensembl_id,]
oranGeneCorrInput <- inputBundle$geneCorrInputCompare
oranGeneCorrInput <- oranGeneCorrInput[rownames(oranGeneCorrInput) %in% ensembl_id,]

# filter gene name and add KAP1
gene.name <- hm337[hm337$ensembl_gene_id %in% rownames(hmGeneCorrInput),]
gene.name <- rbind(gene.name, c("ENSG00000130726", "TRIM28"))

#replace rownames from ensembl_id to gene name
rownames(hmGeneCorrInput) <- gene.name$external_gene_name[match(rownames(hmGeneCorrInput), gene.name$ensembl_gene_id)]

rownames(oranGeneCorrInput) <- gene.name$external_gene_name[
  match(rownames(oranGeneCorrInput), gene.name$ensembl_gene_id)
]

# load TE data
hmTECorrInput <- inputBundle$TECorrInputRef
oranTECorrInput <- inputBundle$TECorrInputCompare

# run correlation
hmCorrResult <- corrOrthologTE(
    geneInput = hmGeneCorrInput,
    teInput = hmTECorrInput,
    corrMethod = "pearson",
    padjMethod = "fdr",
    fileDir = "hmoran_results",
    fileName = "hmCorrResult.csv"
)
oranCorrResult <- corrOrthologTE(
  geneInput = oranGeneCorrInput,
  teInput = oranTECorrInput,
  corrMethod = "pearson",
  padjMethod = "fdr",
  fileDir = "hmoran_results",
  fileName = "oranCorrResult.csv"
)


```

```{r, eval=FALSE}
appTEKRABber(
  DEresult = hmoranDE,
  corrRef = hmCorrResult,
  corrCompare = oranCorrResult,
  metadata = meta
)
```


