---
title: "018_correlation_percentage"
author: "yao"
date: '2022-05-10'
output: html_document
---

Here we try to shuffle data to see the gene have negative or positive 
correlations comparing to approx. 50% KRAB-ZNFs (42 out of 81) in human. 
Design:  
1. remove krab-znfs from data
2. 

Load pacakge
```{r}
library(TEKRABber)
library(twice)
```

Load data and transform to the format for `corrOrthologTE()`

```{r}
data("hmKZNFs337")
gene <- read.csv("counts/hm_gene.csv")
te <- read.csv("counts/hm_te.csv")

# remove krab-znfs from gene
gene_filter <- gene[!(gene$gene %in% hmKZNFs337$ensembl_gene_id), ]
rownames(gene_filter) <- gene_filter$gene
gene_filter <- gene_filter[,c(2,3,4)]

# set row names of TE
rownames(te) <- te$name
te <- te[,c(4,5,6)]

```

```{r}
set.seed(84)
for (i in 1:3){
    idx <- sample(8838, size=80)
    gene_table <- gene_filter[idx, ]
    myfile <- paste0(format(Sys.time(), "%s_%b_%d", ".csv")
    corrOrthologTE(
        gene_table,
        te,
        fileDir = "hm_results/percentage_result/",
        fileName = myfile
    )
}

```


